name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  BOOK_ROOT: "mybook"  # Ganti dengan nama folder root Jupyter Book Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r $BOOK_ROOT/requirements.txt
          pip install jupyter-book ghp-import

      - name: Clean Jupyter Book outputs
        run: |
          jupyter-book clean $BOOK_ROOT --all

      - name: Execute and Build Jupyter Book
        run: |
          jupyter-book build $BOOK_ROOT --builder html \
            --path-output _build \
            --keep-going \
            --overwrite \
            --execute

      - name: Upload executed notebooks (debug only)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebooks
          path: $BOOK_ROOT/**/*.ipynb

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          ghp-import -n -p -f _build/html -b gh-pages