name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  BOOK_ROOT: "mybook"  # Ganti jika folder Anda berbeda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r $BOOK_ROOT/requirements.txt
          pip install jupyter-book ghp-import nbconvert

      - name: Execute all notebooks
        run: |
          find $BOOK_ROOT -name "*.ipynb" -exec jupyter nbconvert --to notebook --inplace --execute {} \;

      - name: Build Jupyter Book
        run: |
          jupyter-book build $BOOK_ROOT

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          ghp-import -n -p -f $BOOK_ROOT/_build/html -b gh-pages